### ISSUE TITLE
Lacking ba-donk-a-donk

### ISSUE THREAD

**Issue by aychedee** [hjwp/pytest-icdiff#1]
https://open.spotify.com/track/39VVNdgGZgKVRblt4SWoeg?si=c2G7jfPSR9iOuf0RX0kyew

**Comment by aychedee** [comment]
This is a pretty serious issue

**Comment by adamchainz** [comment]
[Put a donk on it.](https://www.youtube.com/watch?v=ckMvj1piK58)

**Comment by hjwp** [comment]
https://www.youtube.com/watch?v=IPEOqMCZ2u8
