### ISSUE TITLE
CLI option to disable icdiff

### ISSUE THREAD

**Issue by fschulze** [hjwp/pytest-icdiff#22]
Sometimes it would be helpful to have a ``--no-icdiff`` option to get the original output.

**Comment by tui95** [comment]
Any pytest plugin can be disabled via command line. Just add the flag `-p no:PLUGIN_NAME`.

In this case, the command would be
```shell
pytest -p no:icdiff
```

See [here](https://docs.pytest.org/en/6.2.x/writing_plugins.html#plugin-discovery-order-at-tool-startup) for more details.
