### ISSUE TITLE
Incomplete list of supported Python versions in Badge and on PyPI

### ISSUE THREAD

**Issue by mlegner** [hjwp/pytest-icdiff#31]
The project badge and PyPI page do not list 3.9 and 3.10 as supported Python versions:

![image](https://user-images.githubusercontent.com/5960634/204556451-3ad71d8b-9772-4785-913d-36d23046ec5b.png)

![image](https://user-images.githubusercontent.com/5960634/204556501-e302ee33-63c2-494f-8281-427d77aa00f8.png)

**Comment by hjwp** [comment]
fixed!  thank you
