### ISSUE TITLE
Using within Python

### ISSUE THREAD

**Issue by Kilo59** [hjwp/pytest-icdiff#7]
Is it possible to use this within python outside of Pytest.
Some like....
```python
print(pytest_icdiff.diffs(list1, list2))
```

**Comment by hjwp** [comment]
no, but you can use `icdiff` itself from python, because that's what i do!

example here: https://github.com/hjwp/pytest-icdiff/blob/master/pytest_icdiff.py#L13

more docs heer https://github.com/jeffkaufman/icdiff
