### ISSUE TITLE
why "python_requires='>=3.6'," ?

### ISSUE THREAD

**Issue by jedie** [hjwp/pytest-icdiff#8]
Seems that icdiff and pprintpp doesn't support only python >=3.6 ...

**Comment by hjwp** [comment]
i just don't like python without f-strings any more.  are you stuck on an old version?

**Comment by jedie** [comment]
yes: ubuntu 16.04 has only python 3.5 ;)

**Comment by hjwp** [comment]
can you upgrade? can you use the `deadsnakes` PPA? I really don't want to lose my fstrings if i don't have to...

**Comment by jedie** [comment]
I no longer stay with Python 3.5 🎉
